name: aoc2024
version: 0.0.1
synopsis: Advent of Code 2024 by Daniel Martin

dependencies:
  - base >= 4.7 && < 5
  - containers
  - multiset
  - mtl
  - pqueue
  - vector
  - split
  - text
  - bytestring
  - array
  - linear
  - list-t
  - data-default
  - unordered-containers
language: GHC2021
when:
  - condition: os(windows)
    then:
      ghc-options:
        [
          "-Wall",
          "-O2",
          "+RTS",
          "--io-manager=native",
          "-RTS",
          "-with-rtsopts=--io-manager=native",
          "-rtsopts",
        ]
    else:
      ghc-options: ["-Wall", "-O2", "-rtsopts"]
executables:
  # aoc1: { "main": "aoc1.hs", "source-dirs": "." }
  # aoc2: { "main": "aoc2.hs", "source-dirs": "." }
  # aoc3: { "main": "aoc3.hs", "source-dirs": "." }
  # aoc3b: { "main": "aoc3b.hs", "source-dirs": "." }
  # aoc4: { "main": "aoc4.hs", "source-dirs": "." }
  # aoc5: { "main": "aoc5.hs", "source-dirs": "." }
  # aoc6: { "main": "aoc6.hs", "source-dirs": "." }
  # aoc7: { "main": "aoc7.hs", "source-dirs": "." }
  # aoc8: { "main": "aoc8.hs", "source-dirs": "." }
  # aoc8b: { "main": "aoc8b.hs", "source-dirs": "." }
  # aoc9: { "main": "aoc9.hs", "source-dirs": "." }
  # aoc10: { "main": "aoc10.hs", "source-dirs": "." }
  # aoc11: { "main": "aoc11.hs", "source-dirs": "." }
  # aoc11b: { "main": "aoc11b.hs", "source-dirs": "." }
  # aoc12: { "main": "aoc12.hs", "source-dirs": "." }
  # aoc13: { "main": "aoc13.hs", "source-dirs": "." }
  aoc14: { "main": "aoc14.hs", "source-dirs": "." }
  # aoc15: { "main": "aoc15.hs", "source-dirs": "." }
  # aoc16: { "main": "aoc16.hs", "source-dirs": "." }
  # aoc17: { "main": "aoc17.hs", "source-dirs": "." }
  # aoc18: { "main": "aoc18.hs", "source-dirs": "." }
  # aoc19: { "main": "aoc19.hs", "source-dirs": "." }
  # aoc20: { "main": "aoc20.hs", "source-dirs": "." }
  # aoc21: { "main": "aoc21.hs", "source-dirs": "." }
  # aoc22: { "main": "aoc22.hs", "source-dirs": "." }
  # aoc23: { "main": "aoc23.hs", "source-dirs": "." }
  # aoc24: { "main": "aoc24.hs", "source-dirs": "." }
  # aoc25: { "main": "aoc25.hs", "source-dirs": "." }
